const WA='+94766869930';
function wa(text){window.open('https://wa.me/'+WA.replace(/\D/g,'')+'?text='+encodeURIComponent(text),'_blank')}
function setActive(){const p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a').forEach(a=>{const h=a.getAttribute('href');if(h===p)a.classList.add('active')})}
function toggleMenu(){document.querySelector('.mobile-nav')?.classList.toggle('open')}
window.addEventListener('resize',()=>{if(window.innerWidth>760)document.querySelector('.mobile-nav')?.classList.remove('open')})
function updateCartCount(){const c=JSON.parse(localStorage.getItem('novaCart')||'[]');const n=c.reduce((s,x)=>s+x.qty,0);document.querySelectorAll('#cartCount').forEach(e=>e.textContent=n)}
function addToCart(name,price){const c=JSON.parse(localStorage.getItem('novaCart')||'[]');const x=c.find(i=>i.name===name);if(x)x.qty++;else c.push({name,price,qty:1});localStorage.setItem('novaCart',JSON.stringify(c));updateCartCount();alert(name+' added to enquiry cart.');}
function renderCart(){const box=document.querySelector('#cartBody');if(!box)return;const c=JSON.parse(localStorage.getItem('novaCart')||'[]');if(!c.length){box.innerHTML='<div class="notice">Your enquiry cart is empty. Add products from the catalogue and send us your requirements.</div>';document.querySelector('#cartTotal').textContent='LKR 0';return}let total=0;box.innerHTML='<table class="order-table"><thead><tr><th>Product</th><th>Qty</th><th>Indicative price</th><th></th></tr></thead><tbody>'+c.map((x,i)=>{total+=x.price*x.qty;return `<tr><td>${x.name}</td><td><div class="qty"><button onclick="changeQty(${i},-1)">−</button>${x.qty}<button onclick="changeQty(${i},1)">+</button></div></td><td>${x.price ? 'LKR '+(x.price*x.qty).toLocaleString() : 'Quote on request'}</td><td><button class="btn small light" onclick="removeItem(${i})">Remove</button></td></tr>`}).join('')+'</tbody></table>';document.querySelector('#cartTotal').textContent=total ? 'LKR '+total.toLocaleString() : 'Quotation required'}
function changeQty(i,d){const c=JSON.parse(localStorage.getItem('novaCart')||'[]');c[i].qty+=d;if(c[i].qty<=0)c.splice(i,1);localStorage.setItem('novaCart',JSON.stringify(c));updateCartCount();renderCart()}
function removeItem(i){const c=JSON.parse(localStorage.getItem('novaCart')||'[]');c.splice(i,1);localStorage.setItem('novaCart',JSON.stringify(c));updateCartCount();renderCart()}
function sendCart(){const c=JSON.parse(localStorage.getItem('novaCart')||'[]');if(!c.length)return alert('Please add at least one product.');wa('NovaLink Global Product Enquiry\n\n'+c.map(x=>`${x.name} — Qty: ${x.qty}`).join('\n')+'\n\nPlease send availability, grade, MOQ and quotation.');}
function formSubmit(e){e.preventDefault();const f=new FormData(e.target);let msg='NovaLink Global Enquiry\n\n';for(const [k,v] of f.entries())if(v)msg+=k+': '+v+'\n';wa(msg);}
document.addEventListener('DOMContentLoaded',()=>{setActive();updateCartCount();renderCart();document.querySelectorAll('form.wa-form').forEach(f=>f.addEventListener('submit',formSubmit));});
